[project]
name = "e-commerce-clothing-reviews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.1.0",
    "ipykernel>=7.4.0",
    "loguru>=0.7.3",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "streamlit>=1.65.0",
    "torch>=2.7.1",
    "torchinfo>=1.8.0",
    "transformers>=5.18.0",
    "xgboost>=3.4.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true
