[project]
name = "e-commerce-clothing-reviews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.4.0",
    "loguru>=0.7.3",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "xgboost>=3.4.1",
]
